### PR TITLE
fix build error about filename

### PR DESCRIPTION
**Pull request by yetist**
When run `nikola build`, get build error:
```
[2019-02-18T16:08:52Z] ERROR: Nikola: Two posts are trying to generate blog/2018-02-07-mate-1-20-released/index.html: blog/20180206-mate-1-20-released.md and blog/20180206-mate-1-20-released.zh_CN.md
[2019-02-18T16:08:52Z] ERROR: Nikola: Two posts are trying to generate de/blog/2018-02-07-mate-1-20-released/index.html: blog/20180206-mate-1-20-released.md and blog/20180206-mate-1-20-released.zh_CN.md
[2019-02-18T16:08:52Z] ERROR: Nikola: Two posts are trying to generate el/blog/2018-02-07-mate-1-20-released/index.html: blog/20180206-mate-1-20-released.md and blog/20180206-mate-1-20-released.zh_CN.md
[2019-02-18T16:08:52Z] ERROR: Nikola: Two posts are trying to generate es/blog/2018-02-07-mate-1-20-released/index.html: blog/20180206-mate-1-20-released.md and blog/20180206-mate-1-20-released.zh_CN.md
[2019-02-18T16:08:52Z] ERROR: Nikola: Two posts are trying to generate fr/blog/2018-02-07-mate-1-20-released/index.html: blog/20180206-mate-1-20-released.md and blog/20180206-mate-1-20-released.zh_CN.md
[2019-02-18T16:08:52Z] ERROR: Nikola: Two posts are trying to generate id/blog/2018-02-07-mate-1-20-released/index.html: blog/20180206-mate-1-20-released.md and blog/20180206-mate-1-20-released.zh_CN.md
[2019-02-18T16:08:52Z] ERROR: Nikola: Two posts are trying to generate it/blog/2018-02-07-mate-1-20-released/index.html: blog/20180206-mate-1-20-released.md and blog/20180206-mate-1-20-released.zh_CN.md
[2019-02-18T16:08:52Z] ERROR: Nikola: Two posts are trying to generate nl/blog/2018-02-07-mate-1-20-released/index.html: blog/20180206-mate-1-20-released.md and blog/20180206-mate-1-20-released.zh_CN.md
[2019-02-18T16:08:52Z] ERROR: Nikola: Two posts are trying to generate pl/blog/2018-02-07-mate-1-20-released/index.html: blog/20180206-mate-1-20-released.md and blog/20180206-mate-1-20-released.zh_CN.md
[2019-02-18T16:08:52Z] ERROR: Nikola: Two posts are trying to generate pt/blog/2018-02-07-mate-1-20-released/index.html: blog/20180206-mate-1-20-released.md and blog/20180206-mate-1-20-released.zh_CN.md
[2019-02-18T16:08:52Z] ERROR: Nikola: Two posts are trying to generate tr/blog/2018-02-07-mate-1-20-released/index.html: blog/20180206-mate-1-20-released.md and blog/20180206-mate-1-20-released.zh_CN.md
[2019-02-18T16:08:52Z] ERROR: Nikola: Two posts are trying to generate zh_cn/blog/2018-02-07-mate-1-20-released/index.html: blog/20180206-mate-1-20-released.md and blog/20180206-mate-1-20-released.zh_CN.md
[2019-02-18T16:08:52Z] ERROR: Nikola: Two posts are trying to generate zh_tw/blog/2018-02-07-mate-1-20-released/index.html: blog/20180206-mate-1-20-released.md and blog/20180206-mate-1-20-released.zh_CN.md
```

### CODE REVIEW

**Comment by raveit65** [comment]
@flexiondotorg 
...please review

**Comment by yetist** [comment]
Aha, the last successful compilation is 9ab6e43: https://semaphoreci.com/mate-desktop/mate-desktop-org/branches/master/builds/39
From b1f7cf4 we can't build and update the website:
Https://semaphoreci.com/mate-desktop/mate-desktop-org/branches/master/builds/40

**Comment by yetist** [comment]
So, the website has not been updated in a year?

**Comment by yetist** [comment]
@raveit65 

Oh my God, http://mate-desktop.org show me 404

**Comment by yetist** [comment]
I know the reason, the wrong file name blocked the build process until this PR fixes it. 
With this PR, the build started, but the python script is wrong and no html files are generated. This may be because the python version of the system has been upgraded.

By the way, the results of the PR should only be checked, not directly deployed on the website, only the commits on the master can.

**Comment by yetist** [comment]
The error output from https://semaphoreci.com/mate-desktop/mate-desktop-org/branches/pull-request-107/builds/1

```
Traceback (most recent call last):
  File "/home/runner/.pyenv/3.5/lib/python3.5/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/runner/.pyenv/3.5/lib/python3.5/site-packages/nikola/post.py", line 492, in compile
    self.is_two_file),
  File "/home/runner/.pyenv/3.5/lib/python3.5/site-packages/nikola/plugins/compile/markdown/__init__.py", line 78, in compile_html
    output = markdown(data, self.extensions)
TypeError: markdown() takes 1 positional argument but 2 were given 
```

**Comment by raveit65** [comment]
> By the way, the results of the PR should only be checked, not directly deployed on the website, only the commits on the master can.

I don't think that a PR will directly deploy on a website.

**Comment by yetist** [comment]
Website rebuild, https://github.com/yetist/mate-desktop.org/releases/tag/v19.2.19
- Migrate to use Nikola V8
- Build with Travis CI

Tarballs download address: https://github.com/yetist/mate-desktop.org/releases/download/v19.2.19/website-19.02.19.tar.xz
Complete build log: https://travis-ci.org/yetist/mate-desktop.org/builds/495498170

Now need someone to download the tarball, and deploy it into the web server.

**Comment by selectiveduplicate** [comment]
After ``build serve`` I'm getting two repeated code 404 messages:

```
127.0.0.1 - - [20/Feb/2019 00:34:59] code 404, message File not found: /home/sakib/mate-desktop.org/output/assets/js/all-nocdn.js
127.0.0.1 - - [20/Feb/2019 00:34:59] code 404, message File not found: /home/sakib/mate-desktop.org/output/assets/js/all-nocdn.css
```
And the site renders like this:

mate_desktop_site

Maybe I'm doing something wrong? :confused:

**Comment by yetist** [comment]
Using v19.2.19 tarballs, I didn't find any problems, and I can see the Chinese page of 1.20 release: https://mate.zhcn.cc/zh_cn/blog/2018-02-07-mate-1-20-released/

https://mate.zhcn.cc using the  v19.2.19.tar.xz file.

The official website has been restored, it seems that the old version is used, because the Chinese page of 1.20 release is not visible: https://mate-desktop.org/zh_cn/blog/2018-02-07-mate-1-20-released/

**Comment by raveit65** [comment]
Yes, deployment did killed actual site and @flexiondotorg  restored a backup for the moment.

**Comment by yetist** [comment]
Rebase on master.

**Pull request merged**
