### PR TITLE
fix typos in commit headers from release notes

### PR DESCRIPTION
**Pull request by raveit65**
and delete some duplicate entries

### CODE REVIEW

**Comment by yetist** [comment]
how to do? Maybe to use the git precommit hook?

**Comment by raveit65** [comment]
> Maybe to use the git precommit hook?

This is for eliminating typos?

**Comment by yetist** [comment]
No, just can call spell check tool in it.

**Comment by raveit65** [comment]
Is it a Github App or a webhook?

**Comment by yetist** [comment]
Similar to this https://github.com/mprpic/git-spell-check , for personal use, there is no Github App or webhook, so it's not very useful.

**Pull request merged**
