### PR TITLE
Add Catalan screenshots of MATE 1.22

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
I added core-team to this repo, so you can create branches here.
preview branch: https://github.com/mate-desktop/mate-desktop.org/tree/preview-135
preview should be available in a view minutes
preview.mate-desktop.dev

**Comment by raveit65** [comment]
Preview branch is updated and travis runs.

**Comment by raveit65** [comment]
https://preview.mate-desktop.dev/ca/gallery/1.22/catalan/

**Comment by rbuj** [comment]
@raveit65 thanks
Captures link works at https://preview.mate-desktop.dev/ca/, and it opens the gallery:
https://preview.mate-desktop.dev/ca/gallery/1.22/catalan/

**Pull request merged**
