### PR TITLE
Add missing css code for footerbox class in mate.css

### PR DESCRIPTION
**Pull request by rbuj**
```
$ grep -r footerbox ./output | fgrep -v "class=\"footerbox\""
```

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj 
What element is the footerbox?

**Comment by raveit65** [comment]
@rbuj 
This breaks the footer box.
Bildschirmfoto zu 2019-12-13 12-55-03
I will revert it for the moment.

**Comment by rbuj** [comment]
@raveit65 Ok

**Comment by rbuj** [comment]
New PR https://github.com/mate-desktop/mate-desktop.org/pull/179

**Pull request merged**
