### PR TITLE
Enable Travis CI

### PR DESCRIPTION
**Pull request by yetist**
@raveit65 

Can you enable travis for this repo? thank you.

### CODE REVIEW

**Comment by raveit65** [comment]
Done, looks like a 'git push -f is needed'

**Comment by raveit65** [comment]
Should i merge it?
Or do you want t add more changes?

**Comment by yetist** [comment]
ok, the build is pass, let's merge this pr to master.

**Comment by yetist** [comment]
The gh-pages seems not work now ?

**Comment by yetist** [comment]
I plan to use `preview.mate-desktop.dev` to see every PR's build results, by this repo's gh-pages.

Ideally, each merge request may be viewed through the preview, and after the merge is completed, it is automatically pushed to the official website.

There are two ways to deploy an official website to `www.mate-desktop.org`:
1. use github pages
After travis build the all htmls into output directory, deploy these files into the `organization github page`, it need create a new repo named `mate-desktop.github.io`.
2. use our own server
After travis build the all htmls into output directory, deploy these files into the own own server by run rsync, this need a ssh key.

**Comment by yetist** [comment]
Can you enable gh-pages? So we first see the actual effect of the site until it is satisfied, then consider actually deploying it.

**Comment by yetist** [comment]
@raveit65 

I think the website is ready to deoloy

I think the site is ready for deployment. You can compare https://preview.mate-desktop.dev and https://mate-desktop.org to see what else needs to be modified.

**Comment by yetist** [comment]
BTW, maybe adding a watermark to the preview site would be better? The effect is like this https://yetist.mate-desktop.dev/

**Comment by sc0w** [comment]
I think a watermark to the preview isn't a real preview

**Comment by yetist** [comment]
I prefer to add a watermark to the preview site for the following reasons:
1. The preview website can only temporarily check the effect of a PR, and cannot view the results of multiple PRs at the same time. It needs to have a clear identifier to distinguish which PR result.
2. If the user does not pay attention to the url and only views the page, it is impossible to judge whether this is a preview or an official website, which is easy to cause confusion.
3. The watermark does not have a real impact on the reading of the content of the website.

**Comment by yetist** [comment]
I prefer to add a watermark to the preview site for the following reasons:
1. The preview website can only temporarily check the effect of a PR, and cannot view the results of multiple PRs at the same time. It needs to have a clear identifier to distinguish which PR result.
2. If the user does not pay attention to the url and only views the page, it is impossible to judge whether this is a preview or an official website, which is easy to cause confusion.
3. The watermark does not have a real impact on the reading of the content of the website.

**Comment by raveit65** [comment]
> I plan to use `preview.mate-desktop.dev` to see every PR's build results, by this repo's gh-pages.

Ideally, each merge request may be viewed through the preview, and after the merge is completed, it is automatically pushed to the official website.

> Very nice, this is helpful to review a PR.

There are two ways to deploy an official website to `www.mate-desktop.org`:
1. use github pages
After travis build the all htmls into output directory, deploy these files into the `organization github page`, it need create a new repo named `mate-desktop.github.io`.
2. use our own server
After travis build the all htmls into output directory, deploy these files into the own own server by run rsync, this need a ssh key.

I don't want to switch to gh-pages without finding a consensus with @flexiondotorg 
and having 2 competing websites at the moment.
There are more open questions, eg. how is PayPal page handled, which needs to be solved before.

**Comment by raveit65** [comment]
I think a watermarks is needed to mark the site as non official site.
Maybe the watermark can be more discrete with less text?

**Comment by yetist** [comment]
@raveit65 

The watermarks was added on preview website.

**Comment by raveit65** [comment]
This watermark is much better.
@sc0w 
Is this a consensus for you?

**Comment by sc0w** [comment]
@raveit65 it was only a opinion, no problem :)

**Pull request merged**
