### PR TITLE
Update team member

### PR DESCRIPTION
**Pull request by yetist**
Add yetist to the core team.

### CODE REVIEW

**Comment by raveit65** [comment]
I think this list needs to be cleaned in a next step.
Eg. Stefano was one of the founder of MATE, but he isn't active since 3-4 years.
Calling him Lead developer is a joke nowadays.
Clement Lefebvre (clem) is Mate  founder but still inactive since 3 years for Mate, Well ,he is linuxmint maintainer (head).
I think we need a founder section under contributor where we can mention and honor the 4 founders of MATE.
(Stefano, Perberos, Steve Zech, Clement Lefebvre)
Also, Mike Gabriel (sunweaver) isn't member of core-team. No idea why he is in team here.
He is only MATE debian maintainer and belongs in contributor section.
For me only active people belongs in team section on top.
And @lukefromdc and @sc0w are missing in team section. They were heavily active the last years.

**Comment by yetist** [comment]
I agree with you to modify this part, you know the most.

**Comment by raveit65** [comment]
It's on my list.

**Comment by sc0w** [comment]
@vkareh @yetist 

I don't understand why, but I can see you here, in the preview website:

https://preview.mate-desktop.dev/team/

but I can't see you here, in the official website:

http://mate-desktop.org/team/

**Comment by sc0w** [comment]
...and also I noticed the preview website have more languages than the official website

**Comment by yetist** [comment]
The content of the preview website has not been synced to the server, and the content displayed on the official website is not up to date.

**Comment by sc0w** [comment]
the spanish version and vkareh member was added with https://github.com/mate-desktop/mate-desktop.org/pull/92 since one year ago, it seems all the PRs here are useless?

**Comment by yetist** [comment]
#91 break the website with the wrong file name.

**Comment by vkareh** [comment]
Yeah, I added the Spanish translation a long time ago, but it never got deployed. I think the PRs are fine, but the official website is still serving a _really_ old version...

**Comment by yetist** [comment]
I have a question, why is this repo not given the core team permissions to maintain together? Does anyone know the reason?

**Comment by sc0w** [comment]
I will add one more question: why the donations are handled by someone that never contributes to mate-desktop ? and why the movements of that donations aren't public?

**Comment by raveit65** [comment]
> I have a question, why is this repo not given the core team permissions to maintain together? Does anyone know the reason?

I think this repo was there before core-team was created.
I just added the team to this repo.

**Pull request merged**
