### PR TITLE
convert restructed text to markdown files

### PR DESCRIPTION
**Pull request by raveit65**
I'd like to translate our website with transifex, but unfortunately they don't support .rst (restructed text) files.
In result those files needs to convert to markdown or jason.

There is only one issue after converting.
From https://github.com/mate-desktop/mate-desktop.org/blob/master/pages/index.rst
```
----
News
----

.. post-list::
    :lang: en
    :stop: 5
```
@mate-desktop/core-team @mate-desktop/contributors @mate-desktop/debian-maintainers @mate-desktop/distro-kings @mate-desktop/documentation-team 
Does anyone know how to replace this `rst` syntax ?

### CODE REVIEW

**Comment by mbkma** [comment]
maybe `{{% post-list stop=5 %}}{{% /post-list %}}` works? https://getnikola.com/handbook.html#post-list

**Comment by raveit65** [comment]
Same when i am using `::: {.post-list lang="en" stop="5"}{% /post-list %}`.
Nikola just render the input but not the list.
I used already pandoc like this `pandoc -f rst -t markdown -o index.md index.rst` for converting the file.

**Comment by raveit65** [comment]
Correct syntax is
```
{{% post-list lang="en" stop=5 %}}{{% /post-list %}}
```
:smiley: 

@mbkma 
Thanks
Do you see other issue in preview of website ?
https://preview.mate-desktop.dev/

When it is merged i can add the config at transifex website.

**Review by mbkma — APPROVED** [review]
Everything looks good now. This PR converts some reStructuredText documents to Markdown documents.

**Pull request merged**
