### PR TITLE
Add missing css code for div.footerbox in mate.css

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj 
Same problem again :/
https://mate-desktop.org/

Do we really need to change that?
Everything is working fine without PRs.

**Comment by raveit65** [comment]
@yetist 
Maybe a problem with different Nicola version?
preview use nicola from ArchLinux
Server use debian.

**Comment by raveit65** [comment]
I will revert it again.

**Comment by yetist** [comment]
@raveit65 @rbuj

No. After nicola build, only need a static web server to use.

I guess the css is not work as we want, and the preview site works well because the browser cached the old html files.

**Pull request merged**
