### PR TITLE
Add Hamara Linux in Distribution list. 

### PR DESCRIPTION
**Pull request by Manas-kashyap**
Add Hamara Linux in Distribution list . 
Hamara new release , i,e  Hamara sugam supports MATE officially.

### CODE REVIEW

**Comment by raveit65** [comment]
Can you please rebase this branch against current master and force a push? This should enable Nikola-preview for this PR.

**Comment by raveit65** [comment]
I created https://github.com/mate-desktop/mate-desktop.org/tree/preview-101

**Comment by raveit65** [comment]
Thanks

**Comment by Manas-kashyap** [comment]
Thank you for your response .

**Pull request merged**
