### PR TITLE
add 1.28 release notes

### PR DESCRIPTION
**Pull request by mbkma**
Hi together,

I prepared a template for the release notes of MATE 1.28. Everybody can of course contribute by adding commits to this branch.

#### TODO
- [x] Add About Dialog image
- [x] Write headline changes summary
- [x] Write commit messages for individual packages
- [ ] Do not forget to mention any important changes
- [x] Do a final spell & grammar check

### CODE REVIEW

**Review by lukefromdc — COMMENTED** [review]
These latest additions are really nicely done-and includes a nice improvement on my own wording for the wayland-specific mate-applets stuff.

**Comment by mbkma** [comment]
Please could someone provide a screenshot of the About Dialogue with MATE 1.28 @mate-desktop/core-team ?

**Comment by lukefromdc** [comment]
About_MATE_1 28

**Comment by lukefromdc** [comment]
The line 
`* The dictionary panel applet can be used in a wayland session's panel as well as under x11 if built with wayland support`

should be under mate-utils not under mate-wayland-session as the dictionary applet is part of that package

**Comment by mbkma** [comment]
@lukefromdc done :)

**Review by lukefromdc — APPROVED** [review]
Looks good to me

**Comment by lukefromdc** [comment]
Anyone else want to weigh in or should I merge this?

**Comment by lukefromdc** [comment]
Not seeing it show up at mate-desktop.org , what handles deploying this to the website? No idea if this is lost due to losing Travis

**Comment by lukefromdc** [comment]
We have it in the preview page at
https://preview.mate-desktop.dev/blog/2024-02-27-mate-1-28-released/
but not at
https://mate-desktop.org/blog/
or
https://mate-desktop.org

**Comment by mbkma** [comment]
Yeah, we nned travis. Or alternatively the password for the webserver @raveit65 ?

**Comment by lukefromdc** [comment]
I have no idea whatsoever what the deal is w the Travis situation or how to fix it

**Comment by sameersharma2006** [comment]
@lukefromdc  A small typo in the blog -> At line 209 in blog/20240227-mate-1-28-released.md

```
 Traditional tray icons not displayed as they use Xembed which is not supported in wayland.
```

IMHO this should be

```
 Traditional tray icons are not displayed as they use Xembed which is not supported in wayland.
```

**Comment by clefebvre** [comment]
Hi @lukefromdc, @mbkma,

Are you still using Liberachat? or any other public chat place?

I'd like to get in touch with you to talk about the project, the team and your plans going forward.

**Comment by lukefromdc** [comment]
I myself am not (I limit total online accounts) but no idea if others are

**Comment by lukefromdc** [comment]
We are still up at Travis itself and they just added credits, but I am not seeing the build being triggered from here

**Comment by lukefromdc** [comment]
Not sure there are supposed to be any travis checks from here.

Folks, I do NOT understand how most of the deployment code works, and  in general administering things remotely is a low experience area for me.

**Comment by lukefromdc** [comment]
A worry of mine is this: less overall activity, fewer team members, and I do not have the time or energy to solo maintain the project beyond my own use of it. So many things come up that were never my responsibiliyy now not being done, often in things I have little understanding of like the travis issue.

**Comment by mbkma** [comment]
I just restarted the Travis build for this repo. Release notes should be online soon :) And  i joined the Matrix channel @clefebvre

**Comment by lukefromdc** [comment]
https://mate-desktop.org still does not show 1.28

**Comment by mbkma** [comment]
@lukefromdc PR #737 needs to be merged for the website to deploy. The travis build was broken and #737 fixes that.

**Comment by lukefromdc** [comment]
OK, I will have to take your word on that as I don't know enough about it to evaluate it. We are way behind on this and nobody else seems to be paying attention.

**Comment by lukefromdc** [comment]
1.28 is now on the website

**Pull request merged**
