### PR TITLE
Delete unused files which cannot be found in output

### PR DESCRIPTION
**Pull request by rbuj**
helper bash script:
```shell
OIFS="$IFS"
IFS=$'\n'
for FILE in `find files -type f -not -path "files/assets/img/flags/*"`
do
  res=$(fgrep -r $(basename "$FILE") ./output | wc -l)
  if [ $res -eq 0 ]
  then
    echo "not used: $FILE"
  fi
done
IFS="$OIFS"
```

### CODE REVIEW

**Comment by raveit65** [comment]
Really deleting sharenice?
conf.py and sharenice.js were added here
https://github.com/mate-desktop/mate-desktop.org/commit/f56b1a9cf43f99ef646a6816a807271856583d0c
And i found this repo of sharenice.
https://github.com/mischat/shareNice
http://sharenice.org/
Sounds like a good feature.

**Comment by raveit65** [comment]
Hmm, you are removing `sharenice.js` after forced-push. I am not sure if this is really needed.

**Comment by sc0w** [comment]
@raveit65 see this commit: https://github.com/mate-desktop/mate-desktop.org/commit/c13a294bc765d4afb30b0a4c2deae76d5645ddf5

it was disabled later, safe to remove

**Comment by sc0w** [comment]
`linuxvoice-header.png` safe to remove since the commit https://github.com/mate-desktop/mate-desktop.org/commit/2bddab7c14bc4b6ee4364c1890db886ae547723c

`gplus.png` and `wiki.png` safe to remove since the commit https://github.com/mate-desktop/mate-desktop.org/commit/04abf4aec31620e06d9a11e60372ab4c6fe87574

`translate.png` safe to remove since the commit https://github.com/mate-desktop/mate-desktop.org/commit/6f603f641a3573e5a546e6e148d5ebc2e8f26f18

`sharenice.js` safe to remove since the commit https://github.com/mate-desktop/mate-desktop.org/commit/c13a294bc765d4afb30b0a4c2deae76d5645ddf5

`Screenshop.jpg` was added with https://github.com/mate-desktop/mate-desktop.org/commit/4b2c8629ff6d0296dc416f32d0c4f6c21b7d019b but it is unused

**Pull request merged**
