### PR TITLE
migrate to use Nikola v8

### PR DESCRIPTION
**Pull request by yetist**
Upgrade website to use nikola v8

### CODE REVIEW

**Comment by raveit65** [comment]
Cool, so we can enable Nikola again at server?

**Comment by yetist** [comment]
No, according to the nikola website, nikola v8 only valid on archlinux, so, if you enable another ci, it use ubuntu may be break website again.
But, dont worry, I have another way to deploy own website.
And now I need you to enable gh-pages for this repo.

**Comment by raveit65** [comment]
Gh-pages should be enabled.
Not sure, but i think our webside is on an debian server.
I need access to website.......

**Comment by raveit65** [comment]
> No, according to the nikola website, nikola v8 only valid on archlinux, so, if you enable another ci, it use ubuntu may be break website again.

So, nikola v8 needs to run on website server too?

**Comment by yetist** [comment]
> So, nikola v8 needs to run on website server too?

Nikola v8 does not need to run on the server, just upload the compilation results to the server.

**Comment by raveit65** [comment]
> Nikola v8 does not need to run on the server, just upload the compilation results to the server.

Hmm, i thought `autoload deployment` on server was part of Nikola, or not?

**Comment by yetist** [comment]
No, nikola's deploy is actually running user-defined commands, that commands can be run directly on travis. 

https://github.com/mate-desktop/mate-desktop.org/blob/05418e2c8244b8bc9954e6dc0deadba10cce4373/conf.py#L668

**Comment by raveit65** [comment]
Ok, but this command doesn't reload the website, or not?
My understanding of Nikola was that it can auto reload a website on a server. Is that right?
And that merging a PR here at github did broke the website in the past.

I only like to understand how this work.

**Comment by yetist** [comment]
It works as follows:
Nikola converts the markdown source file into a static website consisting of html and saves it to the output directory, simply upload the contents of this directory to the appropriate directory on the web server.

Previously, we used rsync on ssh to upload these files, now we can deploy it like this, but I don't have permission to upload files.

**Comment by raveit65** [comment]
Ok, got it.
I think `rsync` was done with a cronjob at server.

**Comment by yetist** [comment]
@raveit65 

Do you have permission to add an ssh public key on the server? If you have, the website deploy can be completed soon.

**Comment by raveit65** [comment]
I waiting for an answer to get access form @flexiondotorg

**Pull request merged**
