### PR TITLE
Add OS108

### PR DESCRIPTION
**Pull request by jaypatelani**

### CODE REVIEW

**Comment by raveit65** [comment]
Can you please squash all commit in one?
Use the `git rebase -i <last-commit-before-yours-id>` in your local repo.
After all is done, do a `git push --force` to upload your changes to github.
PR will be updated automatic.

**Comment by jaypatelani** [comment]
did it :)

**Comment by raveit65** [comment]
But i see here 15 single commits?

**Comment by jaypatelani** [comment]
Hi please check if I did it correctly..  Thanks

**Comment by raveit65** [comment]
Thanks, this looks better. But it is also possible to `reword` a commit with that command :)
To avoid:
```
From c1f3027ae6ac3dac7645832cb5a82110c2f8ff22 Mon Sep 17 00:00:00 2001
From: Jay Patel <jaypatelani@gmail.com>
Date: Wed, 24 Apr 2019 17:09:48 +0000
Subject: [PATCH] added OS108

Update index.rst

Added OS108

Added OS108

Added OS108

Added OS108

Added OS108

Added OS108

Added OS108

Added OS108

Added OS108

Added OS108

Added OS108

Added OS108

Added OS108
---
 pages/index.ca.rst    | 1 +
 pages/index.de.rst    | 1 +
 pages/index.el.rst    | 1 +
 pages/index.es.rst    | 1 +
 pages/index.fr.rst    | 1 +
 pages/index.hu.rst    | 1 +
 pages/index.id.rst    | 1 +
 pages/index.it.rst    | 1 +
 pages/index.pl.rst    | 1 +
 pages/index.pt.rst    | 1 +
 pages/index.rst       | 1 +
 pages/index.tr.rst    | 1 +
 pages/index.zh_cn.rst | 1 +
 pages/index.zh_tw.rst | 1 +
 14 files changed, 14 insertions(+)

diff --git a/pages/index.ca.rst b/pages/index.ca.rst
index 7d08b369d8..de9899e888 100644
--- a/pages/index.ca.rst
+++ b/pages/index.ca.rst
<cut>
```

**Comment by sc0w** [comment]
This PR has two commits, and first commit (Update hungarian team page) seems to be unrelated

**Comment by raveit65** [comment]
@sc0w 
I think the unrelated commit will be gone when rebase+merge the PR.

**Comment by raveit65** [comment]
Reworded and merged.
https://github.com/mate-desktop/mate-desktop.org/commit/0c1bc43bc0a54a80a9d0d5ec8d5663c6312ff282
Thank you

**Pull request closed without merging**
