### PR TITLE
Added MATE 1.20 screenshots. 

### LINKED ISSUE #90: Add screenshots for 1.20
The current one is from 1.14 and it is quite outdated. I would be happy to provide new screenshots.

### PR DESCRIPTION
**Pull request by VentGrey**
Since MATE 1.20 is out for a while  I took tome "Vanilla" screenshots to show users how does it look like now. My system's language is spanish so I don't know if that would cause a problem with the english version.

Edit:
This also fixes #90

### CODE REVIEW

**Comment by raveit65** [comment]
Can you please rebase this branch against current master and force a push? This should enable Nikola-preview for this PR.

**Comment by VentGrey** [comment]
All ready :smile:

**Comment by raveit65** [comment]
Hmm, i said rebase not merge :-/
Now we have a merge commit.
Well, i can cherry-pick your commits by hand.

Any way, i don't see our new preview page under checks.
@yetist 
Any idea why this doesn't work for older PRs?

**Comment by raveit65** [comment]
Or maybe provide screenshots for both languages?

**Comment by VentGrey** [comment]
Might take some time but I think I can upload them today :D

**Comment by sc0w** [comment]
The screenshots here only works in english(default) and spanish

The screenshots are in spanish, so, the PR is ok for me if it works only in spanish language

anyway, it would be nice to add english language screenshots, of course :)

**Comment by raveit65** [comment]
Ok, it is only done if spanish language is selected, thanks for that :P   
Maybe you think whole the world speaks spanish ? 
Any way i don't really mind :)
But why replacing 1.14 dir with 1.20 ?
It wont hurt to keep the old screenshots.

**Comment by raveit65** [comment]
Forgot my last comment , i was wrong with conf.py
Older screenshots are always accessible.
But i think half of the PR will be obsolete after https://github.com/mate-desktop/mate-desktop.org/pull/128
I added screenshot for 1.22 release.
Maybe adding only the screenshots is sufficient?

**Comment by sc0w** [comment]
I did it in https://github.com/mate-desktop/mate-desktop.org/pull/147

**Comment by raveit65** [comment]
We merged first commit to  master https://github.com/mate-desktop/mate-desktop.org/commit/6e4abfef30df52fc26a6983f44873033cdeff755
Thanks

**Pull request closed without merging**
