### PR TITLE
Add css for kbd element in mate.css

### PR DESCRIPTION
**Pull request by rbuj**
Sample: MATE 1.20 Released

Captura de pantalla a 2019-12-12 20-31-43

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj 
After re-run https://travis-ci.org/mate-desktop/mate-desktop.org/builds/624302899 generate the preview again, i do not see you proposed changes in preview.
https://preview.mate-desktop.dev/blog/2018-02-07-mate-1-20-released/

Note: we only see the preview of last PR or commit in master. For older PRs you need to run travis again.

**Comment by rbuj** [comment]
It's only a `git rebase master` and `git push -f` to get the preview.

**Comment by raveit65** [comment]
> It's only a `git rebase master` and `git push -f` to get the preview.

That's true but only another way to update actual preview.
For me it is easier to restart the build again with the restart button at travis website.

Any way, PR is fixed and i see you changes now in preview.

**Comment by raveit65** [comment]
Ahh Ok,
so the rebase from master was missing, got it.

**Pull request merged**
