### PR TITLE
Add Hungarian translation of pages

### PR DESCRIPTION
**Pull request by meskobalazs**
The translations of blog posts will arrive in later PRs.

### CODE REVIEW

**Comment by yetist** [comment]
Please see the preview website,  https://preview.mate-desktop.dev/ , is that ok?

**Comment by yetist** [comment]
https://preview.mate-desktop.dev/hu/, here seems not good:
```
Többet találhat a `MATE <gallery/1.22/> képernyőképei`_ között.
```

**Comment by meskobalazs** [comment]
I have fixed the issue.

**Comment by yetist** [comment]
You can visit https://mate-desktop.org/ to see the result, thank you.

**Comment by raveit65** [comment]
@meskobalazs 
Team page is wrong.
https://preview.mate-desktop.dev/hu/team/
Can you update Hungarian team page for matching original English page, please?
https://preview.mate-desktop.dev/team/

**Comment by vkareh** [comment]
I updated the team page: #157

**Pull request merged**
