### PR TITLE
Team page fixes

### PR DESCRIPTION
**Pull request by vkareh**
* Updated the hungarian team page
* Fix broken link for perberos

### CODE REVIEW

**Comment by vkareh** [comment]
@meskobalazs - could you review the hungarian page? I had to make some changes to update the team list.

**Comment by sc0w** [comment]
@mate-desktop/core-team 

It is possible to work the translations of website with transifex as the other repositories?

it will avoid us a lot of work

**Comment by raveit65** [comment]
Maybe....
...i dunno

**Comment by yetist** [comment]
maybe use this one？ https://github.com/gisce/markdown-i18n

**Comment by yetist** [comment]
@vkareh @raveit65 

What about this? https://gitlocalize.com
The translate page is here (looks like transifex):  https://gitlocalize.com/repo/1752/zh-CN/blog/20130326new-themes.md
The review page: https://gitlocalize.com/repo/1752/zh-CN/review/8630/segments
The pull request created here: https://github.com/yetist/mate-desktop.org/pull/1

I don't know more about that, I just tried it. Maybe you can try it.

**Comment by raveit65** [comment]
I am sure we can also use transifex.
But i don't have the time to figure it out at the moment.
....Next MATE release will be in one year probably :)
Btw. @flexiondotorg @monsta  and @rbuj  are admins at transifex too.....

**Comment by flexiondotorg** [comment]
@raveit65 I asked about using Transifex for handling Nikola translations. Sadly, it's not supported.

**Pull request merged**
