### PR TITLE
Add Slint among distributions supporting Mate.

### PR DESCRIPTION
**Pull request by DidierSpaier**

### CODE REVIEW

**Comment by vkareh** [comment]
@DidierSpaier - can you squash all your commits locally into one? Not really worth it having 15 separate commits in the git history for the same thing

**Comment by DidierSpaier** [comment]
@vkareh How do I do that? My knowledge of git is below sea level...

**Comment by vkareh** [comment]
In your computer, navigate to the directory where you cloned the repo and run `git rebase -i HEAD~15` then change the `pick` to `fixup` in all except the first entry. Save and exit and then `git push --force` to push back here.

**Comment by DidierSpaier** [comment]
Will do another PR instead

**Pull request closed without merging**
