### PR TITLE
Add Japanese screenshots of MATE 1.24 

### PR DESCRIPTION
**Pull request by usergreen**
Add Japanese screenshots of MATE 1.24

### CODE REVIEW

**Comment by usergreen** [comment]
Canllelation was my mistake, because I am not used to do like this.

**Comment by usergreen** [comment]
Typo:
Canllelation was my mistake, because I am not used to do like this. -->
Cancellation was my mistake, because I am not used to do like this.

**Comment by raveit65** [comment]
There are no Japanese screenshots in preview of our website https://preview.mate-desktop.dev/ja/gallery/1.24/english/
I think you need to update conf.py like this https://github.com/mate-desktop/mate-desktop.org/commit/768574bf2db456a5585eec7eeaf3d4f5c6c7291f  (example).

**Comment by usergreen** [comment]
Thank raveit65, I updated conf.py file thoroughly.

**Comment by raveit65** [comment]
With a local website build from your branch i see your screenshots.
Bildschirmfoto zu 2021-08-22 21-54-30
Bildschirmfoto zu 2021-08-22 21-55-02
So i think it is OK.
Thanks for the screenshots.

**Review by raveit65 — APPROVED** [review]
LGTM

**Comment by mbkma** [comment]
sorry I see this too late, but the screenshots are from MATE 1.20.4 not MATE 1.24

**Comment by raveit65** [comment]
Looks good :)
https://mate-desktop.org/gallery/1.24/japanese/

**Comment by raveit65** [comment]
OMG, i didn't expect such a mistake.
@usergreen 
Why you add screenshoots  from 1.20.3 to 1.24 gallery?
@mbkma 
Should i revert commits?

**Comment by usergreen** [comment]
To raveit65
I am sorry. I am using both MATE 1.20 and MATE 1.24 here, so did not noticed for sure. these MATE 1.20 images will be re-uploaded later to a proper directory.

**Comment by usergreen** [comment]
As for MATE 1.24 screenshots, they are coming up soon.

**Comment by usergreen** [comment]
MATE 1.24 screenshots were re-uploaded, and old images ware all deleted at my local repository.

**Comment by mbkma** [comment]
@raveit65 I think https://github.com/mate-desktop/mate-desktop.org/pull/709 fixes the issue, I have no time to test it right now though.

**Comment by usergreen** [comment]
Thanks all, I am not quite sure these process, but there are fixed  files in my repository.
mbkma,  so that, you can delete this fork.

**Comment by usergreen** [comment]
Hello mbkma,
Fom now on, I am going to delete my own fork repository, and after that screenshots will be uploaded again to right directories.
Is it alright for you?

**Pull request merged**
