### PR TITLE
update Travis CI build environment

### PR DESCRIPTION
**Pull request by yetist**

### CODE REVIEW

**Comment by sc0w** [comment]
deprecated skip_cleanup can be fixed here too?

**Comment by raveit65** [comment]
> deprecated skip_cleanup can be fixed here too?

@yetist ^^^^

**Comment by raveit65** [comment]
@sc0w @yetist 
Should be OK with last commit. Ready to merge?

**Comment by sc0w** [comment]
maybe these warnings can be fixed here or in other PR?



and maybe is better `- DISTRO="archlinux:latest"` like we did in other repositories?

**Comment by raveit65** [comment]
> maybe these warnings can be fixed here or in other PR?
> and maybe is better - DISTRO="archlinux:latest" like we did in other repositories?

As team member you can update PRs.

**Pull request merged**
